version: '3'
services:
    php:
        build:
          context: .
          dockerfile: ./.docker/Dockerfile
        container_name: php_example
        ports:
          - 8081:80
        volumes:
          - ./:/var/www/html